import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';



SizedBox sizedBoxH1 = SizedBox(height: 1.h);
SizedBox sizedBoxH2 = SizedBox(height: 2.h);
SizedBox sizedBoxH3 = SizedBox(height: 3.h);
SizedBox sizedBoxH4 = SizedBox(height: 4.h);
SizedBox sizedBoxH5 = SizedBox(height: 5.h);
SizedBox sizedBoxH6 = SizedBox(height: 6.h);
SizedBox sizedBoxH7 = SizedBox(height: 7.h);
SizedBox sizedBoxH8 = SizedBox(height: 8.h);
SizedBox sizedBoxH10 = SizedBox(height: 10.h);
SizedBox sizedBoxH12 = SizedBox(height: 12.h);
SizedBox sizedBoxH13 = SizedBox(height: 13.h);
SizedBox sizedBoxH14 = SizedBox(height: 14.h);
SizedBox sizedBoxH15 = SizedBox(height: 15.h);
SizedBox sizedBoxH16 = SizedBox(height: 16.h);
SizedBox sizedBoxH18 = SizedBox(height: 18.h);
SizedBox sizedBoxH20 = SizedBox(height: 20.h);
SizedBox sizedBoxH22 = SizedBox(height: 22.h);
SizedBox sizedBoxH23 = SizedBox(height: 23.h);
SizedBox sizedBoxH25 = SizedBox(height: 25.h);
SizedBox sizedBoxH28 = SizedBox(height: 28.h);
SizedBox sizedBoxH30 = SizedBox(height: 30.h);
SizedBox sizedBoxH34 = SizedBox(height: 34.h);
SizedBox sizedBoxH35 = SizedBox(height: 35.h);
SizedBox sizedBoxH36 = SizedBox(height: 36.h);
SizedBox sizedBoxH40 = SizedBox(height: 40.h);
SizedBox sizedBoxH43 = SizedBox(height: 43.h);
SizedBox sizedBoxH45 = SizedBox(height: 45.h);
SizedBox sizedBoxH50 = SizedBox(height: 50.h);
SizedBox sizedBoxH60 = SizedBox(height: 60.h);
SizedBox sizedBoxH70 = SizedBox(height: 70.h);
SizedBox sizedBoxH80 = SizedBox(height: 80.h);
SizedBox sizedBoxH110 = SizedBox(height: 110.h);

SizedBox sizedBoxW1 = SizedBox(width: 1.w);
SizedBox sizedBoxW2 = SizedBox(width: 2.w);
SizedBox sizedBoxW3 = SizedBox(width: 3.w);
SizedBox sizedBoxW4 = SizedBox(width: 4.w);
SizedBox sizedBoxW5 = SizedBox(width: 5.w);
SizedBox sizedBoxW6 = SizedBox(width: 6.w);
SizedBox sizedBoxW8 = SizedBox(width: 8.w);
SizedBox sizedBoxW10 = SizedBox(width: 10.w);
SizedBox sizedBoxW12 = SizedBox(width: 12.w);
SizedBox sizedBoxW13 = SizedBox(width: 13.w);
SizedBox sizedBoxW14 = SizedBox(width: 14.w);
SizedBox sizedBoxW16 = SizedBox(width: 16.w);
SizedBox sizedBoxW18 = SizedBox(width: 18.w);
SizedBox sizedBoxW20 = SizedBox(width: 20.w);
SizedBox sizedBoxW26 = SizedBox(width: 26.w);
SizedBox sizedBoxW30 = SizedBox(width: 30.w);
SizedBox sizedBoxW40 = SizedBox(width: 40.w);
SizedBox sizedBoxW50 = SizedBox(width: 50.w);
SizedBox sizedBoxW60 = SizedBox(width: 60.w);
SizedBox sizedBoxW65 = SizedBox(width: 65.w);
SizedBox sizedBoxW70 = SizedBox(width: 70.w);
